PLANS = {
    "starter": {
        "name": "Standard",
        "price": 50,
        "annual_price": 500,
        "tagline": "For schools starting a supervised wellbeing workflow",
        "limits": "Up to 300 students",
        "student_limit": 300,
        "staff_limit": 25,
        "extra_student_fee": "$0.20/student/month after included limit",
        "extra_student_note": "After 300 students, extra seats should be approved before billing. Keep the policy explicit in the sales agreement.",
        "best_for": "Small and mid-size schools starting a supervised support workflow.",
        "trial_note": "30 days for evaluation before paid billing starts.",
        "features": [
            "30-day free trial",
            "Student check-ins and journals",
            "Teacher aggregate classroom pulse",
            "Counselor support workflow",
            "Consent center",
            "Basic reports and exports",
            "Email support",
        ],
    },
    "growth": {
        "name": "Pro",
        "price": 120,
        "annual_price": 1200,
        "tagline": "For active support teams that need deeper workflows",
        "limits": "Up to 1,000 students",
        "student_limit": 1000,
        "staff_limit": 80,
        "extra_student_fee": "$0.15/student/month after included limit",
        "extra_student_note": "After 1,000 students, extra seats should be approved before billing or moved to a custom agreement.",
        "best_for": "Schools with active counseling teams and deeper operational workflows.",
        "trial_note": "30 days for evaluation before paid billing starts.",
        "features": [
            "30-day free trial",
            "Everything in Standard",
            "Nour AI-assisted companion history",
            "Support-plan and case timeline workflow",
            "Advanced group analytics",
            "CSV import",
            "Priority support",
        ],
    },
    "scale": {
        "name": "Custom",
        "price": 0,
        "annual_price": 0,
        "tagline": "For districts, multi-campus groups, and large deployments",
        "limits": "Above 1,000 students",
        "student_limit": 5000,
        "staff_limit": 250,
        "extra_student_fee": "Negotiated",
        "extra_student_note": "Custom pricing for districts, multi-campus groups, data residency needs, or large rollout support.",
        "best_for": "Large schools, districts, and multi-campus groups that need guided rollout terms.",
        "trial_note": "Usually starts as a guided pilot rather than a self-serve checkout.",
        "features": [
            "Guided pilot option",
            "Everything in Pro",
            "Multi-campus controls",
            "Advanced exports",
            "Security review pack",
            "Launch readiness support",
            "Negotiated annual agreement",
        ],
    },
}

ROLES = ("student", "teacher", "counselor", "admin")
RISK_LEVELS = ("steady", "watch", "support", "urgent")

ONBOARDING_TASKS = (
    ("profile", "Complete school profile"),
    ("billing", "Choose monthly, annual, or guided pilot billing"),
    ("consent", "Add consent and privacy policy owner"),
    ("staff", "Create counselor and teacher accounts"),
    ("students", "Import or create student accounts"),
    ("protocol", "Review the human escalation protocol"),
)
