import os
import re
import tempfile
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

os.environ.setdefault("AUTO_INIT_DB", "true")
os.environ.setdefault("SEED_DEMO_DATA", "true")
os.environ.setdefault("SECRET_KEY", "route-audit-secret")

from schoolmind import create_app

EXPECTED_ENDPOINTS = {
    "public.index",
    "public.product",
    "public.features",
    "public.pricing",
    "public.demo",
    "public.request_demo",
    "public.contact_sales",
    "public.human_review",
    "public.compliance",
    "public.cookies",
    "public.contact",
    "public.public_preferences",
    "public.personalize_preferences",
    "public.privacy",
    "public.terms",
    "public.safety",
    "public.sitemap_xml",
    "public.robots_txt",
    "public.subprocessors",
    "public.data_retention",
    "public.accessibility",
    "public.faq",
    "public.pilot",
    "public.students",
    "public.counselors",
    "public.teachers",
    "public.schools",
    "auth.login",
    "auth.google_start",
    "auth.google_callback",
    "auth.start",
    "auth.forgot_password",
    "dashboard.student_home",
    "dashboard.account_settings",
    "dashboard.help_center",
    "dashboard.activity_center",
    "dashboard.student_assessment",
    "dashboard.journal_studio",
    "dashboard.companion_studio",
    "dashboard.nour_messages_api",
    "dashboard.student_goals",
    "dashboard.games",
    "dashboard.progress_hub",
    "dashboard.weekly_summary",
    "dashboard.support_plans",
    "dashboard.breathing_center",
    "dashboard.resources",
    "dashboard.mood_diary",
    "dashboard.daily_tips",
    "dashboard.teacher_home",
    "dashboard.counselor_home",
    "dashboard.counselor_create_plan",
    "dashboard.admin_home",
    "dashboard.admin_operations",
    "dashboard.admin_plan_limits",
    "dashboard.admin_security",
    "dashboard.admin_backups",
    "dashboard.admin_database",
    "dashboard.admin_billing",
    "api.health",
    "api.readiness",
    "api.export_workspace_json",
    "api.billing_webhook",
    "platform.platform_login",
    "platform.platform_home",
    "platform.platform_account_settings",
    "platform.platform_coupons",
    "platform.platform_coupon_status",
    "platform.platform_settings",
}

PUBLIC_GETS = [
    "/",
    "/product",
    "/features",
    "/pricing",
    "/demo",
    "/request-demo",
    "/contact-sales",
    "/human-review",
    "/compliance",
    "/cookies",
    "/contact",
    "/privacy",
    "/terms",
    "/safety",
    "/sitemap.xml",
    "/robots.txt",
    "/subprocessors",
    "/data-retention",
    "/accessibility",
    "/faq",
    "/pilot",
    "/students",
    "/counselors",
    "/teachers",
    "/schools",
    "/login",
    "/start",
    "/forgot-password",
    "/auth/google",
    "/api/health",
    "/api/readiness",
    "/platform/login",
]

PROTECTED_GETS = [
    "/app",
    "/student",
    "/settings/account",
    "/help",
    "/activity",
    "/journal",
    "/companion",
    "/goals",
    "/games",
    "/progress",
    "/weekly-summary",
    "/support-plans",
    "/breathing-center",
    "/resources",
    "/mood-diary",
    "/daily-tips",
    "/teacher",
    "/counselor",
    "/admin",
    "/admin/operations",
    "/admin/plan-limits",
    "/admin/security",
    "/admin/backups",
    "/admin/database",
    "/platform",
    "/platform/account",
    "/platform/coupons",
    "/platform/settings",
]


def main():
    tmp = tempfile.NamedTemporaryFile(delete=False)
    tmp.close()
    try:
        app = create_app({"TESTING": True, "DATABASE_PATH": tmp.name, "SECRET_KEY": "route-audit-secret"})
        endpoints = {rule.endpoint for rule in app.url_map.iter_rules()}
        missing = sorted(EXPECTED_ENDPOINTS - endpoints)
        if missing:
            raise SystemExit(f"Missing expected endpoints: {missing}")

        client = app.test_client()
        failures = []
        for path in PUBLIC_GETS:
            response = client.get(path)
            if response.status_code >= 400:
                failures.append(f"{path} returned {response.status_code}")
        for path in PROTECTED_GETS:
            response = client.get(path)
            if response.status_code not in {302, 403}:
                failures.append(f"{path} expected auth boundary, returned {response.status_code}")
        if failures:
            raise SystemExit("Route audit failed:\n" + "\n".join(failures))

        lines = ["# Route Map", "", "Generated by `scripts/route_audit.py`.", ""]
        for rule in sorted(app.url_map.iter_rules(), key=lambda r: (r.rule, r.endpoint)):
            methods = ",".join(sorted(rule.methods - {"HEAD", "OPTIONS"}))
            lines.append(f"- `{rule.rule}` — `{methods}` — `{rule.endpoint}`")
        (ROOT / "docs" / "ROUTE_MAP.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"Route audit passed: {len(endpoints)} endpoints checked.")
    finally:
        try:
            os.unlink(tmp.name)
        except FileNotFoundError:
            pass


if __name__ == "__main__":
    main()
